### ISSUE TITLE
.kick should kick

### ISSUE THREAD

**Issue by zuzak** [SteamDatabase/Wendy#26]
`.kick` currently `/remove`s people if the relevant configuration setting is set, which makes me sad.

**Comment by xPaw** [comment]
I think it's a good idea to remove users instead of using kick, as auto-join plugins make it almost entirely useless. Perhaps sending a notice on remove would be a good idea.

**Comment by RJacksonm1** [comment]
So what do you want me to do?

**Comment by zuzak** [comment]
Override behaviour to always kick on `.kick` and add a `.rm` command that removes (or kicks if that config variable 'ain't set).

Or alternatively think of a better way to do things

**Comment by xPaw** [comment]
There are two separate commands for this in Wendy#
