### ISSUE TITLE
Do that twitter thing with steam store links too

### ISSUE THREAD

**Issue by zuzak** [SteamDatabase/Wendy#34]
Youtube and Twitter links get nice context from Wendy as to what I'm about to click. Considering the channel Wendy is in, it really should do something with store.steampowered.com links too.

**Comment by RJacksonm1** [comment]
What kinda data do you want exposing?  Also, should data be pulled from Steam or SteamDB (wendy can scrape no problem)?

**Comment by xPaw** [comment]
SteamDB bot does it now.
